# Generated by Django 6.0.3 on 2026-03-20 19:23

import item_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(default='Med', max_length=50, validators=[item_app.validators.validate_size])),
                ('photo', models.CharField(default='https://www.pngall.com/wp-content/uploads/5/Clothing-Hanger-PNG-High-Quality-Image.png', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
