# Generated by Django 6.0.3 on 2026-03-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
