# Generated by Django 6.0.3 on 2026-03-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0002_alter_item_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
