# Generated by Django 6.0.3 on 2026-03-25 21:18

import item_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0003_alter_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(default='M', max_length=50, validators=[item_app.validators.validate_size]),
        ),
    ]
