# Generated by Django 6.0.3 on 2026-03-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0004_alter_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='Misc', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
